services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spike
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d spike"]
      interval: 5s
      retries: 5

  backend:
    # Contains api key for groq usage
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      target: production
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/spike
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}  # make sure to create the .env in the base directory and paste the tokens from discord in it
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
    ports:
      - "8000:8000"
    command: ["sh", "-c", "python -m alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl localhost:8000/health"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://backend:8000
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]        # override the CMD from the Dockerfile
    depends_on:
      backend:
        condition: service_healthy
