services:
  backend:
    # Contains api key for groq usage
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      target: production
    ports:
      - "8000:8000"
    command: ["sh", "-c", "python -m alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --port 8000"]
    healthcheck:
      test: "curl localhost:8000/health"
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      INTERNAL_API_URL: http://backend:8000
      NEXT_PUBLIC_API_BASE_URL: /api
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]        # override the CMD from the Dockerfile
    depends_on:
      backend:
        condition: service_healthy
