FROM public.ecr.aws/lambda/python:3.11

COPY requirements-runtime.txt requirements-api.txt ${LAMBDA_TASK_ROOT}/
RUN pip install \
    --disable-pip-version-check \
    --no-cache-dir \
    -r ${LAMBDA_TASK_ROOT}/requirements-api.txt

COPY app ${LAMBDA_TASK_ROOT}/app
COPY lambdas/__init__.py lambdas/common.py lambdas/schedule.py lambdas/public_discussion_schedule.py ${LAMBDA_TASK_ROOT}/lambdas/
COPY main.py lambda_api.py viewer.html ${LAMBDA_TASK_ROOT}/

CMD ["lambda_api.handler"]
